baseURL: https://darmajalaya.github.io/
languageCode: en-us
title: Darmajalaya
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
          author: author

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Darmajalaya
  description: "Learn by doing"
  keywords: [Blog, Portfolio, Tutorials, Hugo, Website Static Site, PaperMod]
  author: darmajalaya 
  images: ["/icons/iconapi.svg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "icons/favicon.ico"
    favicon16x16: "icons/favicon-16x16.png"
    favicon32x32: "icons/favicon-32x32.png"
    apple_touch_icon: "icons/apple-touch-icon.png"
    safari_pinned_tab: "icons/iconapi.svg"

  label:
    text: "Darmajalaya"
    icon: /icons/iconapi.svg
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Darmajalaya
    subtitle: "Learn by doing"
    imageUrl: "/icons/iconapi.svg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: darmajalaya
    buttons:
      - name: Blog
        url: posts
      - name: About
        url: about
    #  - name: Tutorials
    #    url: tags
    #  - name: Projects
    #    url: categories
    #  - name: About
    #    url: about

  # home-info mode
  homeInfoParams:
    Title: "Hi Everyone \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/darmajalaya"
    - name: facebook
      url: "https://facebook.com/darmajalaya"
    - name: github
      url: "https://github.com//darmajalaya"
    - name: discord
      url: "https://discord.com/darmajalaya#2947"
    - name: pip
      url: "https://www.pip.me/darmajalaya.sol"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  # cover image thumbnail true and false
  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: false
    linkFullImages: true

#  editPost:
#    URL: "https://github.com/<path_to_repo>/content"
#    Text: "Suggest Changes" # edit text
#    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "author", "content"]

menu:
  main:
    - identifier: categories
      name: Tutorials
      url: /categories/
      weight: 10
    - identifier: tags
      name: Articles
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

timeout: 30000
enableInlineShortcodes: true

taxonomies:
  category: categories
  tag: tags
  series: series

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true
    disableInlineCSS: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true
